{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "This tutorial is composed of the [FEniCSs tutorial (legacy version)](https://github.com/hplgit/fenics-tutorial/) and the [FEniCSx tutorial](https://jsdokken.com/dolfinx-tutorial/chapter1/fundamentals.html). "
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Mathematical problem formulation\n",
    "\n",
    "Many books on programming languages start with a \"Hello, World!\"\n",
    "program. Readers are curious to know how fundamental tasks are\n",
    "expressed in the language, and printing a text to the screen can be\n",
    "such a task. In the world of *finite element methods for PDEs*, the\n",
    "most fundamental task must be to solve the Poisson equation. Our\n",
    "counterpart to the classical \"Hello, World!\" program therefore\n",
    "solves the following boundary-value problem: We want to solve\n",
    "\n",
    "$$\\begin{align}\n",
    "-\\Delta u(x) &= f(x),\\quad &&x\\text{ in } \\Omega,\\tag{1}\\\\\n",
    "u(x) &= u_D(x),\\quad &&x\\text{ on } \\partial \\Omega\\tag{2}\n",
    "\\end{align}$$\n",
    "\n",
    "where\n",
    "$u = u(x)$ is the unknown function, $f = f(x)$ is a\n",
    "prescribed function, $\\Delta$ is the Laplace operator\n",
    "(also written as $\\nabla^2$), $\\Omega$ is the spatial domain, and\n",
    "$\\partial\\Omega$ is the boundary of $\\Omega$. The Poisson problem,\n",
    "including both the PDE $-\\Delta u = f$ and the boundary condition\n",
    "$u = u_D$ on $\\partial \\Omega$, is an example of a *boundary-value\n",
    "problem*, which must be precisely stated before\n",
    "it makes sense to start solving it with FEniCSx."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Poisson's equation\n",
    "\n",
    "In two space dimensions with coordinates $x$ and $y$, we can write out\n",
    "the Poisson equation as\n",
    "\n",
    "\\begin{equation}\n",
    "- {\\partial^2 u\\over\\partial x^2} - {\\partial^2 u\\over\\partial y^2} = f(x,y)\\tag{3}\n",
    "\\end{equation}\n",
    "\n",
    "The unknown $u$ is now a function of two variables, $u = u(x,y)$, defined\n",
    "over a two-dimensional domain $\\Omega$.\n",
    "\n",
    "The Poisson equation arises in numerous physical contexts, including\n",
    "heat conduction, electrostatics, diffusion of substances, twisting of\n",
    "elastic rods, inviscid fluid flow, and water waves. Moreover, the\n",
    "equation appears in numerical splitting strategies for more complicated\n",
    "systems of PDEs, in particular the Navier-Stokes equations.\n",
    "\n",
    "Solving a boundary-value problem such as the Poisson equation in\n",
    "FEniCSx consists of the following steps:\n",
    "\n",
    "1. Identify the computational domain ($\\Omega$), the PDE, its boundary conditions, and source terms ($f$).\n",
    "1. Reformulate the PDE as a finite element variational problem.\n",
    "1. Write a Python program which defines the computational domain,\n",
    "    the variational problem, the boundary conditions, and source\n",
    "    terms, using the corresponding FEniCSx abstractions.\n",
    "1. Call FEniCSx to solve the boundary-value problem and, optionally,\n",
    "    extend the program\n",
    "    to compute derived quantities such as fluxes and averages, and\n",
    "    visualize the results.\n",
    "\n",
    "We shall now go through steps 2-4 in detail. The key feature of\n",
    "FEniCSx is that steps 3 and 4 result in fairly short code, while a\n",
    "similar program in most other software frameworks for PDEs require\n",
    "much more code and technically difficult programming."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "vscode": {
     "languageId": "plaintext"
    }
   },
   "source": [
    "**💡 What makes FEniCSx attractive?**\n",
    "Although many software frameworks have a really elegant\n",
    "\"Hello, World!\" example for the\n",
    "Poisson equation, FEniCSx is to our knowledge the only framework where\n",
    "the code stays compact and nice, very close to the mathematical\n",
    "formulation, even when the mathematical and algorithmic complexity\n",
    "increases and when moving from a laptop to a high-performance\n",
    "compute server (cluster)."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Finite element variational formulation\n",
    "\n",
    "FEniCSx is based on the finite element method, which is a general and\n",
    "efficient mathematical machinery for the numerical solution of\n",
    "PDEs. The starting point for the finite element methods is a PDE\n",
    "expressed in *variational form*. Readers who are not familiar with\n",
    "variational problems will get a very brief introduction to the topic\n",
    "in this tutorial, but reading a proper book on the finite element\n",
    "method in addition is encouraged. Experience shows that you can work with\n",
    "FEniCSx as a tool to solve PDEs even without thorough knowledge of\n",
    "the finite element method, as long as you get somebody to help you\n",
    "with formulating the PDE as a variational problem.\n",
    "\n",
    "The basic recipe for turning a PDE into a variational problem is to\n",
    "multiply the PDE by a function $v$, integrate the resulting equation\n",
    "over the domain $\\Omega$, and perform integration by parts of terms\n",
    "with second-order derivatives. The function $v$ which multiplies the\n",
    "PDE is called a *test function*. The unknown function $u$ to be\n",
    "approximated is referred to as a *trial function*. The terms trial and\n",
    "test functions are used in FEniCS programs too. The trial and test\n",
    "functions belong to certain so-called *function spaces* that specify\n",
    "the properties of the functions.\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "In the present case, we first multiply the Poisson equation\n",
    "by the test function $v$ and integrate over $\\Omega$:\n",
    "\n",
    "\\begin{equation}\n",
    "-\\int_\\Omega (\\Delta u)v \\;\\text{d}x = \\int_\\Omega fv \\;\\text{d}x\\tag{4}\n",
    "\\end{equation}\n",
    "\n",
    "We here let $\\text{d}x$ denote the differential element for integration over\n",
    "the domain $\\Omega$. We will later let $\\text{d}s$ denote the differential\n",
    "element for integration over the boundary of $\\Omega$.\n",
    "\n",
    "A common rule when we derive variational formulations is that we try\n",
    "to keep the order of the derivatives of $u$ and $v$ as small as\n",
    "possible. Here, we have a second-order spatial derivative of $u$,\n",
    "which can be transformed to a first-derivative of $u$ and $v$ by\n",
    "applying the technique of [\"integration by parts\"](https://en.wikipedia.org/wiki/Integration_by_parts\").\n",
    "The formula reads\n",
    "\n",
    "\\begin{equation}\n",
    "-\\int_\\Omega (\\Delta u)v \\;\\text{d}x\n",
    "= \\int_\\Omega\\nabla u\\cdot\\nabla v \\;\\text{d}x - \\int_{\\partial\\Omega}{\\partial u\\over\n",
    "\\partial n}v \\;\\text{d}s ,\\tag{5}\n",
    "\\end{equation}\n",
    "where $\\frac{\\partial u}{\\partial n} = \\nabla u \\cdot n$ is the\n",
    "derivative of $u$ in the outward normal direction $n$ on the\n",
    "boundary.\n",
    "\n",
    "Another feature of variational formulations is that\n",
    "the test function $v$ is required to vanish on the parts of\n",
    "the boundary where the solution $u$ is known (the book cite{Langtangen_Mardal_FEM_2016} explains in detail why this requirement is necessary).\n",
    "In the present\n",
    "problem, this means that $v=0$ on the whole boundary $\\partial\\Omega$.\n",
    "The second term on the right-hand side of\n",
    "(5) therefore vanishes. From\n",
    "(4) and (5) it\n",
    "follows that\n",
    "\n",
    "\\begin{equation}\n",
    "\\int_\\Omega\\nabla u\\cdot\\nabla v \\;\\text{d}x = \\int_\\Omega fv \\;\\text{d}x\\tag{6}\n",
    "\\end{equation}\n",
    "\n",
    "If we require that this equation holds for all test functions $v$ in\n",
    "some suitable space $\\hat V$, the so-called *test space*, we obtain a\n",
    "well-defined mathematical problem that uniquely determines the\n",
    "solution $u$ which lies in some (possibly different) function space\n",
    "$V$, the so-called *trial space*.  We refer to\n",
    "(6) as the *weak form* or *variational form* of\n",
    "the original boundary-value problem\n",
    "(1)-(2)."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "The proper statement of\n",
    "our variational problem now goes as follows:\n",
    "find $u \\in V$ such that\n",
    "\n",
    "\\begin{equation}\\tag{7}\n",
    "  \\int_{\\Omega} \\nabla u \\cdot \\nabla v \\;\\text{d}x =\n",
    "  \\int_{\\Omega} fv \\;\\text{d}x\n",
    "  \\quad \\forall v \\in \\hat{V}\n",
    "\\end{equation}\n",
    "\n",
    "The trial and test spaces $V$ and $\\hat V$ are in the present\n",
    "problem defined as\n",
    "\n",
    "\\begin{align*}\n",
    "     V      &= \\{v \\in H^1(\\Omega) : v = u_D \\text{ on } \\partial\\Omega\\}, \\\\\n",
    "    \\hat{V} &= \\{v \\in H^1(\\Omega) : v = 0 \\text{ on } \\partial\\Omega\\}\n",
    "\\end{align*}\n",
    "\n",
    "In short, $H^1(\\Omega)$ is the mathematically well-known Sobolev space\n",
    "containing functions $v$ such that $v^2$ and $|\\nabla v|^2$ have\n",
    "finite integrals over $\\Omega$ (essentially meaning that the functions\n",
    "are continuous). The solution of the underlying PDE must lie in a\n",
    "function space where the derivatives are also continuous, but the\n",
    "Sobolev space $H^1(\\Omega)$ allows functions with discontinuous\n",
    "derivatives. This weaker continuity requirement of $u$ in the\n",
    "variational statement (7), as a result of the\n",
    "integration by parts, has great practical consequences when it comes\n",
    "to constructing finite element function spaces. In particular, it\n",
    "allows the use of piecewise polynomial function spaces; i.e., function\n",
    "spaces constructed by stitching together polynomial functions on simple\n",
    "domains such as intervals, triangles, or tetrahedrons.\n",
    "\n",
    "The variational problem (7) is a *continuous\n",
    "problem*: it defines the solution $u$ in the infinite-dimensional\n",
    "function space $V$. The finite element method for the Poisson equation\n",
    "finds an approximate solution of the variational problem\n",
    "(7) by replacing the infinite-dimensional function\n",
    "spaces $V$ and $\\hat{V}$ by *discrete* (finite-dimensional) trial and\n",
    "test spaces $V_h\\subset{V}$ and $\\hat{V}_h\\subset\\hat{V}$. The discrete variational problem reads: find $u_h \\in\n",
    "V_h \\subset V$ such that\n",
    "\n",
    "\\begin{equation}\\tag{8}\n",
    "  \\int_{\\Omega} \\nabla u_h \\cdot \\nabla v \\;\\text{d}x =\n",
    "  \\int_{\\Omega} fv \\;\\text{d}x\n",
    "  \\quad \\forall v \\in \\hat{V}_h \\subset \\hat{V}\n",
    "\\end{equation}\n",
    "\n",
    "This variational problem, together with a suitable definition of the\n",
    "function spaces $V_h$ and $\\hat{V}_h$, uniquely define our approximate\n",
    "numerical solution of Poisson's equation (1). Note\n",
    "that the boundary conditions are encoded as part of the trial and test\n",
    "spaces. The mathematical framework may seem complicated at first\n",
    "glance, but the good news is that the finite element variational\n",
    "problem (8) looks the same as the continuous\n",
    "variational problem (7), and FEniCSx can\n",
    "automatically solve variational problems like (8)!"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "**💡 What we mean by the notation $u$ and $V$:**\n",
    "The mathematics literature on variational problems writes $u_h$ for\n",
    "the solution of the discrete problem and $u$ for the solution of the\n",
    "continuous problem. To obtain (almost) a one-to-one relationship\n",
    "between the mathematical formulation of a problem and the\n",
    "corresponding FEniCSx program, we shall drop the subscript $_h$ and use\n",
    "$u$ for the solution of the discrete problem.\n",
    "We will use $u_e$ for the exact\n",
    "solution of the continuous problem, if we need to explicitly distinguish\n",
    "between the two. Similarly, we will let $V$ denote the discrete finite\n",
    "element function space in which we seek our solution."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Abstract finite element variational formulation\n",
    "\n",
    "It turns out to be convenient to introduce the following canonical\n",
    "notation for variational problems: find $u\\in V$ such that\n",
    "\n",
    "\\begin{equation}\\tag{9}\n",
    "a(u, v) = L(v) \\quad \\forall v \\in \\hat{V}.\n",
    "\\end{equation}\n",
    "\n",
    "For the Poisson equation, we have:\n",
    "\n",
    "\\begin{align}\n",
    "a(u, v) &= \\int_{\\Omega} \\nabla u \\cdot \\nabla v \\;\\text{d}x,\\tag{10}\\\\\n",
    "L(v) &= \\int_{\\Omega} fv \\;\\text{d}x\\tag{11}\n",
    "\\end{align}\n",
    "\n",
    "From the mathematics literature, $a(u,v)$ is known as a *bilinear\n",
    "form* and $L(v)$ as a *linear form*.  We shall, in every linear problem\n",
    "we solve, identify the terms with the unknown $u$ and collect them in\n",
    "$a(u,v)$, and similarly collect all terms with only known functions in\n",
    "$L(v)$. The formulas for $a$ and $L$ can then be expressed directly in\n",
    "our FEniCSx programs.\n",
    "\n",
    "To solve a linear PDE in FEniCSx, such as the Poisson equation, a user\n",
    "thus needs to perform only two steps:\n",
    "\n",
    "  * Choose the finite element spaces $V$ and $\\hat V$ by specifying\n",
    "    the domain (the mesh) and the type of function space (polynomial\n",
    "    degree and type).\n",
    "  * Express the PDE as a (discrete) variational problem: find $u\\in V$\n",
    "    such that $a(u,v) = L(v)$ for all $v\\in \\hat{V}$."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Choosing a test problem\n",
    "\n",
    "The Poisson problem (1)-(2) has so\n",
    "far featured a general domain $\\Omega$ and general functions $u_D$ for\n",
    "the boundary conditions and $f$ for the right-hand side. For our first\n",
    "implementation we will need to make specific choices for $\\Omega$,\n",
    "$u_D$, and $f$. It will be wise to construct a problem with a known\n",
    "analytical solution so that we can easily check that the computed\n",
    "solution is correct. Solutions that are lower-order polynomials are\n",
    "primary candidates. Standard finite element function spaces of degree\n",
    "$r$ will exactly reproduce polynomials of degree $r$. And piecewise\n",
    "linear elements ($r=1$) are able to exactly reproduce a quadratic\n",
    "polynomial on a uniformly partitioned mesh. This important result can\n",
    "be used to verify our implementation. We just manufacture some\n",
    "quadratic function in 2D as the exact solution, say\n",
    "\n",
    "\\begin{equation}\n",
    "u_e(x,y) = 1 +x^2 + 2y^2\\tag{12}\n",
    "\\end{equation}\n",
    "\n",
    "By inserting (12) into the Poisson equation\n",
    "(1), we find that $u_e(x,y)$ is a solution if\n",
    "\n",
    "\\begin{equation}\n",
    "f(x,y) = -6,\\quad u_D(x,y)=u_e(x,y)=1 + x^2 + 2y^2,\n",
    "\\end{equation}\n",
    "\n",
    "regardless of the shape of the domain as long as $u_e$ is prescribed along\n",
    "the boundary. We choose here, for simplicity,\n",
    "the domain to be the unit square,\n",
    "\n",
    "\\begin{equation}\n",
    "\\Omega = ]0,1[\\times ]0,1[\n",
    "\\end{equation}\n",
    "\n",
    "This simple but very powerful method for constructing test problems is\n",
    "called the *method of manufactured solutions*: pick a simple\n",
    "expression for the exact solution, plug it into the equation to obtain\n",
    "the right-hand side (source term $f$), then solve the equation with\n",
    "this right-hand side and using the exact solution as a boundary\n",
    "condition, and try to reproduce the exact solution."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "**💡 Tip:**\n",
    "Try to verify your code with exact numerical solutions!\n",
    "A common approach to testing the implementation of a numerical method\n",
    "is to compare the numerical\n",
    "solution with an exact analytical solution of the test problem and\n",
    "conclude that the program works if the error is \"small enough\".\n",
    "Unfortunately, it is impossible to tell if an error of size $10^{-5}$ on a\n",
    "$20\\times 20$ mesh of linear elements is the expected (in)accuracy of the\n",
    "numerical approximation or if the error also contains the effect of a\n",
    "bug in the code. All we usually know about the numerical error is its\n",
    "*asymptotic properties*, for instance that it is proportional to $h^2$\n",
    "if $h$ is the size of a cell in the mesh. Then we compare the\n",
    "error on meshes with different $h$-values to see if the asymptotic\n",
    "behavior is correct. This is a very powerful verification\n",
    "technique and is explained in detail later on."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## FEniCSx implementation\n",
    "\n",
    "### The complete program\n",
    "\n",
    "A FEniCSx program for solving our test problem for the Poisson equation\n",
    "in 2D with the given choices of $\\Omega$, $u_D$, and $f$ may look as\n",
    "follows:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from mpi4py import MPI\n",
    "import numpy as np\n",
    "from dolfinx import mesh, fem, plot, io\n",
    "from dolfinx.fem.petsc import LinearProblem\n",
    "from ufl import SpatialCoordinate, TrialFunction, TestFunction, inner, grad, dx\n",
    "\n",
    "# Create mesh and define function space\n",
    "msh = mesh.create_unit_square(\n",
    "    comm=MPI.COMM_WORLD,\n",
    "    nx=8,\n",
    "    ny=8\n",
    ")\n",
    "\n",
    "V = fem.functionspace(\n",
    "    mesh=msh,\n",
    "    element=(\"P\", 1)\n",
    ")\n",
    "\n",
    "# Define boundary condition\n",
    "def on_boundary(x):\n",
    "    return np.isclose(x[0], 0) | np.isclose(x[0], 1) | np.isclose(x[1], 0) | np.isclose(x[1], 1)\n",
    "\n",
    "boundary_dofs = fem.locate_dofs_geometrical(V=V, marker=on_boundary)\n",
    "\n",
    "def manufactured_solution(x):\n",
    "    return 1 + x[0]**2 + 2 * x[1]**2\n",
    "\n",
    "uD = fem.Function(V)\n",
    "uD.interpolate(manufactured_solution)\n",
    "\n",
    "bc = fem.dirichletbc(value=uD, dofs=boundary_dofs)\n",
    "\n",
    "# Define variational problem\n",
    "u = TrialFunction(V)\n",
    "v = TestFunction(V)\n",
    "f = fem.Constant(msh, -6.)\n",
    "a = inner(grad(u), grad(v)) * dx\n",
    "L = f * v * dx\n",
    "\n",
    "# Compute solution\n",
    "problem = LinearProblem(a, L, bcs=[bc], petsc_options={\"ksp_type\": \"preonly\", \"pc_type\": \"lu\"})\n",
    "uh = problem.solve()\n",
    "\n",
    "# Plot solution and mesh\n",
    "import pyvista\n",
    "\n",
    "cells, types, x = plot.vtk_mesh(V)\n",
    "grid = pyvista.UnstructuredGrid(cells, types, x)\n",
    "grid.point_data[\"u\"] = uh.x.array.real\n",
    "grid.set_active_scalars(\"u\")\n",
    "plotter = pyvista.Plotter()\n",
    "plotter.add_mesh(grid, show_edges=True)\n",
    "warped = grid.warp_by_scalar()\n",
    "plotter.add_mesh(warped)\n",
    "plotter.show()\n",
    "\n",
    "# Save solution to file in VTX format\n",
    "with io.VTXWriter(msh.comm, \"results/poisson.bp\", [uh]) as vtx:\n",
    "    vtx.write(0.0)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Running the program\n",
    "\n",
    "The FEniCSx program must be available in a plain text file, written with a\n",
    "text editor such as Nano, Vim, VS Code, VSCodium or similar.\n",
    "There are several ways to run a Python program like `poisson.py`:\n",
    "\n",
    " * Use a terminal window.\n",
    " * Use an integrated development environment (IDE), e.g. Spyder, VS Code or VSCodium.\n",
    " * Use a Jupyter notebook.\n",
    "\n",
    " ```\n",
    " python poisson.py\n",
    " ```\n",
    "\n",
    " ⚠️ Note that this command must be run in a FEniCSx-enabled terminal. For users of FEniCSx in Conda, this means that you must type\n",
    "this command after you have started a FEniCS session using `conda activate fenicsx-env`, or by selecting the FEniCSx Conda environment in your IDE or Jupyter notebook, respectively."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Dissection of the program\n",
    "\n",
    "We shall now dissect our FEniCSx program in detail.  The listed FEniCSx\n",
    "program defines a finite element mesh, a finite element function space\n",
    "$V$ on this mesh, boundary conditions for $u$ (the function $u_D$),\n",
    "and the bilinear and linear forms $a(u,v)$ and $L(v)$. Thereafter, the\n",
    "solution $u$ is computed. At the end of the program, we compare the\n",
    "numerical and the exact solutions. We also save the solution to a file for external\n",
    "postprocessing."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### The important first lines\n",
    "\n",
    "The first lines in the program,\n",
    "\n",
    "```python\n",
    "from mpi4py import MPI\n",
    "import numpy as np\n",
    "from dolfinx import mesh, fem, plot, io\n",
    "from dolfinx.fem.petsc import LinearProblem\n",
    "from ufl import TrialFunction, TestFunction, inner, grad, dx\n",
    "```\n",
    "\n",
    "import the key classes `Mesh`, `FunctionSpace`, `Function`,\n",
    "and so forth, from the FEniCSx library.  All FEniCSx programs for\n",
    "solving PDEs by the finite element method normally start with these\n",
    "lines, possibly with additional imports depending on the problem at hand."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Generating simple meshes\n",
    "\n",
    "The statement\n",
    "\n",
    "```python\n",
    "msh = mesh.create_unit_square(\n",
    "    comm=MPI.COMM_WORLD,\n",
    "    nx=8,\n",
    "    ny=8\n",
    ")\n",
    "```\n",
    "\n",
    "defines a uniform finite element mesh over the unit square\n",
    "$[0,1]\\times [0,1]$. The mesh consists of *cells*, which in 2D by default are triangles\n",
    "with straight sides. The argument `comm=MPI.COMM_WORLD` refers to an \n",
    "MPI communicator for parallel computing and will be discussed at a later stage.\n",
    "The parameters `nx=8` and `ny=8` specify that the square\n",
    "should be divided into $8\\times 8$ rectangles, each divided into a pair of\n",
    "triangles. The total number of triangles (cells) thus becomes\n",
    "128. The total number of vertices in the mesh is $9\\cdot 9=81$.\n",
    "In later chapters, you will learn how to generate more complex meshes."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Defining the finite element function space\n",
    "\n",
    "Once the mesh has been created, we can create a finite element\n",
    "function space `V`:\n",
    "\n",
    "```python\n",
    "V = fem.functionspace(\n",
    "    mesh=msh,\n",
    "    element=(\"P\", 1)\n",
    ")\n",
    "```\n",
    "\n",
    "The second argument `(\"P\", 1)` defines the finite element to be used for\n",
    "the function space.\n",
    "\n",
    "`\"P\"` specifies the type of element. The type of\n",
    "element here is $\\mathsf{P}$, implying the standard Lagrange family of\n",
    "elements. You may also use `\"Lagrange\"` to specify this type of\n",
    "element. FEniCSx supports the element families and the notation\n",
    "defined in the [\"DefElement\" encyclopedia of finite element definitions](https://defelement.com/lists/implementations/basix.html).\n",
    "\n",
    "The `1` specifies the degree of the finite element.  In\n",
    "this case, the standard $\\mathsf{P}_1$ linear Lagrange element, which\n",
    "is a triangle with nodes at the three vertices. Some finite element\n",
    "practitioners refer to this element as the \"linear triangle\". The\n",
    "computed solution $u$ will be continuous across elements and linearly\n",
    "varying in $x$ and $y$ inside each element. Higher-degree polynomial\n",
    "approximations over each cell are trivially obtained by increasing this\n",
    "parameter in the `element`, which will then generate function\n",
    "spaces of type $\\mathsf{P}_2$, $\\mathsf{P}_3$, and so forth.  Changing\n",
    "the parameter from `\"P\"` to `\"DP\"` creates a function space for\n",
    "discontinuous Galerkin methods."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Defining the boundary conditions\n",
    "\n",
    "The next step is to specify the boundary condition: $u=u_D$ on\n",
    "$\\partial\\Omega$. This is done by\n",
    "\n",
    "```python\n",
    "bc = fem.dirichletbc(\n",
    "    value=uD,\n",
    "    dofs=boundary_dofs\n",
    ")\n",
    "```\n",
    "\n",
    "where `uD` is a function defining the solution values on the\n",
    "boundary, and `boundary_dofs` is an array that lists\n",
    "which points / degrees of freedom lie on the boundary.\n",
    "\n",
    "Boundary conditions of the type $u=u_D$ are known as *Dirichlet\n",
    "conditions*. For the present finite element method for the Poisson\n",
    "problem, they are also called *essential boundary conditions*, as they\n",
    "need to be imposed explicitly as part of the trial space (in contrast\n",
    "to being defined implicitly as part of the variational formulation).\n",
    "Naturally, the FEniCSx function used to define Dirichlet boundary\n",
    "conditions is named `dirichletbc`.\n",
    "\n",
    "The variable `uD` refers to a `Function` object, which is used to\n",
    "represent a mathematical function on a finite element function space `V`.\n",
    "`uD` is typically constructed by first defining the mathematical function as\n",
    "a Python function. This function may depend on the variables `x[0]` and `x[1]`\n",
    "corresponding to the $x$ and $y$ coordinates. In 3D, the function\n",
    "may also depend on the variable `x[2]` corresponding to the $z$\n",
    "coordinate. With our choice of $u_D(x,y)=1 + x^2 + 2y^2$, the formula\n",
    "can be written as `1 + x[0]**2 + 2 * x[1]**2*`:\n",
    "\n",
    "```python\n",
    "def manufactured_solution(x):\n",
    "    return 1 + x[0]**2 + 2 * x[1]**2\n",
    "```\n",
    "\n",
    "This Python function is now interpolated into the finite element function space:\n",
    "\n",
    "```python\n",
    "uD = fem.Function(V)\n",
    "uD.interpolate(manufactured_solution)\n",
    "```\n",
    "\n",
    "The array `boundary_dofs` specifies which points belong to the\n",
    "part of the boundary where the boundary condition should be applied. FEniCSx\n",
    "offers two ways of locating boundaries:\n",
    "* geometrical\n",
    "* topological\n",
    "\n",
    "Here we use the geometrical way.\n",
    "\n",
    "```python\n",
    "def on_boundary(x):\n",
    "    return np.isclose(x[0], 0) | np.isclose(x[0], 1) | np.isclose(x[1], 0) | np.isclose(x[1], 1)\n",
    "\n",
    "boundary_dofs = fem.locate_dofs_geometrical(V=V, marker=on_boundary)\n",
    "```\n",
    "\n",
    "A function like `on_boundary` for marking the boundary must return a\n",
    "boolean value: `True` if the given point `x` lies on the Dirichlet\n",
    "boundary and `False` otherwise.  The\n",
    "`on_boundary` function will be called for every discrete point in the\n",
    "mesh, which means that we may define boundaries where $u$ is also\n",
    "known inside the domain, if desired.\n",
    "\n",
    "⚠️ Comparing floating-point values using an exact match test with\n",
    "`==` is not good programming practice, because small round-off errors\n",
    "in the computations of the `x` values could make a test `x[0] == 1`\n",
    "become false even though `x` lies on the boundary.  A better test is\n",
    "to check for equality with a tolerance, either explicitly\n",
    "\n",
    "```python\n",
    "tol = 1E-14\n",
    "def on_boundary(x):\n",
    "    return abs(x[0]) < tol | abs(x[0] - 1) < tol |  abs(x[1]) < tol | abs(x[1] - 1) < tol\n",
    "```\n",
    "\n",
    "or using the `isclose` command in NumPy:\n",
    "\n",
    "```python\n",
    "def on_boundary(x):\n",
    "    return np.isclose(x[0], 0) | np.isclose(x[0], 1) | np.isclose(x[1], 0) | np.isclose(x[1], 1)\n",
    "\n",
    "boundary_dofs = fem.locate_dofs_geometrical(V=V, marker=on_boundary)\n",
    "```\n",
    "\n",
    "⚠️ Never use `==` for comparing real numbers!\n",
    "A comparison like `x[0] == 1` should never be used if `x[0]` is a real\n",
    "number, because rounding errors in `x[0]` may make the test fail even\n",
    "when it is mathematically correct. Consider the following calculations\n",
    "in Python:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "0.1 + 0.2 == 0.3"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "0.1 + 0.2"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Comparison of real numbers needs to be made with tolerances! The\n",
    "values of the tolerances depend on the size of the numbers involved in\n",
    "arithmetic operations:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "abs(0.1 + 0.2 - 0.3)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "abs(1.1 + 1.2 - 2.3)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "abs(10.1 + 10.2 - 20.3)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "abs(100.1 + 100.2 - 200.3)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "abs(1000.1 + 1000.2 - 2000.3)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "abs(10000.1 + 10000.2 - 20000.3)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "For numbers of unit size, tolerances as low as $3\\times 10^{-16}$ can be used.\n",
    "Otherwise, an appropriately scaled tolerance must be used."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Defining the trial and test functions\n",
    "\n",
    "In mathematics, we distinguish between the trial and test spaces $V$\n",
    "and $\\hat{V}$. The only difference in the present problem is the\n",
    "boundary conditions. In FEniCSx we do not specify the boundary\n",
    "conditions as part of the function space, so it is sufficient to work\n",
    "with one common space `V` for both the trial and test functions in the\n",
    "program:\n",
    "\n",
    "```python\n",
    "u = TrialFunction(V)\n",
    "v = TestFunction(V)\n",
    "```"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Defining the source term\n",
    "\n",
    "Before defining the bilinear and linear forms $a(u,v)$ and $L(v)$ we\n",
    "have to specify the source term $f$:\n",
    "\n",
    "```python\n",
    "f = -6\n",
    "```\n",
    "\n",
    "This is a simple example of an expression in UFL (Unified Form Language).\n",
    "\n",
    "💡 When $f$ depends on the spatial coordinates $x$ and $y$, then UFL expressions can be defined like in the following example:\n",
    "\n",
    "```python\n",
    "from ufl import exp\n",
    "x = SpatialCoordinate(msh)\n",
    "f = 10 * exp(-((x[0] - 0.5) ** 2 + (x[1] - 0.5) ** 2) / 0.02)\n",
    "```\n",
    "\n",
    "A list of mathematical functions that can be used directly in UFL is available [in the documentation](https://fenics.readthedocs.io/projects/ufl/en/latest/manual/form_language.html#basic-nonlinear-functions).\n",
    "\n",
    "When $f$ however is constant over the domain, `f` can be\n",
    "more efficiently represented as a `Constant`:\n",
    "\n",
    "```python\n",
    "f = fem.Constant(msh, -6.)\n",
    "```\n",
    "\n",
    "⚠️ Note that `Constant` expects a floating-point value for the constant and will not automatically convert `int` to `float`. Thus,\n",
    "\n",
    "```python\n",
    "f = fem.Constant(msh, -6)\n",
    "```\n",
    "\n",
    "raises an error message, whereas `float(-6)`, `-6.0` or `-6.` (with the decimal point included) are accepted."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Defining the variational problem\n",
    "\n",
    "We now have all the ingredients we need to define the\n",
    "variational problem:\n",
    "\n",
    "```python\n",
    "a = inner(grad(u), grad(v)) * dx\n",
    "L = f * v * dx\n",
    "```\n",
    "\n",
    "In essence, these two lines specify the PDE to be solved.  Note the\n",
    "very close correspondence between the Python syntax and the\n",
    "mathematical formulas $\\nabla u\\cdot\\nabla v \\;\\text{d}x$ and $fv \\;\\text{d}x$.  This\n",
    "is a key strength of FEniCSx: the formulas in the variational\n",
    "formulation translate directly to very similar Python code, a feature\n",
    "that makes it easy to specify and solve complicated PDE problems.\n",
    "\n",
    "💡 **Expressing inner products:** The inner product\n",
    "$\\int_{\\Omega} \\nabla u \\cdot \\nabla v \\;\\text{d}x$\n",
    "can be expressed in various ways in FEniCSx. Above, we have used\n",
    "the notation `inner(grad(u), grad(v)) * dx`, but we could have equally used\n",
    "`dot(grad(u), grad(v)) * dx`. The dot product in\n",
    "FEniCSx/UFL computes the sum (contraction) over the last index\n",
    "of the first factor and the first index of the second factor.\n",
    "In this case, both factors are tensors of rank one (vectors) and\n",
    "so the sum is just over the one single index of both $\\nabla u$\n",
    "and $\\nabla v$. To compute an inner product of matrices (with\n",
    "two indices), one must instead of `dot` use the function `inner`.\n",
    "For vectors, `dot` and `inner` are equivalent."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Forming and solving the linear system\n",
    "\n",
    "Having defined the finite element variational problem and boundary\n",
    "condition, we can now ask FEniCSx to compute the solution:\n",
    "\n",
    "```python\n",
    "problem = LinearProblem(a, L, bcs=[bc], petsc_options={\"ksp_type\": \"preonly\", \"pc_type\": \"lu\"})\n",
    "uh = problem.solve()\n",
    "```\n",
    "\n",
    "The `LinearProblem` class provides an interface to PETSc (Portable, Extensible Toolkit for Scientific Computation) as a linear algebra backend. It passes the bilinear form `a`, the linear form `L` and the boundary conditions `bc` to PETSc, so that the discrete linear system of equations can be assembled. The `petsc_options` are passed as a dictionary of settings, which allow fine-tuning of the solver to the problem at hand. Here we use LU decomposition, i.e. Gaussian elimination, to solve for `uh`."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Plotting the solution using PyVista\n",
    "\n",
    "Once the solution has been computed, it can be visualized with PyVista:\n",
    "\n",
    "```python\n",
    "import pyvista\n",
    "\n",
    "cells, types, x = plot.vtk_mesh(V)\n",
    "grid = pyvista.UnstructuredGrid(cells, types, x)\n",
    "grid.point_data[\"u\"] = uh.x.array.real\n",
    "grid.set_active_scalars(\"u\")\n",
    "plotter = pyvista.Plotter()\n",
    "plotter.add_mesh(grid, show_edges=True)\n",
    "warped = grid.warp_by_scalar()\n",
    "plotter.add_mesh(warped)\n",
    "plotter.show()\n",
    "```\n",
    "\n",
    "💡 PyVista is useful for debugging and initial scientific\n",
    "investigations. More advanced visualizations are better created by\n",
    "exporting the solution to a file and using an advanced visualization\n",
    "tool like ParaView, as explained in the next section.\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Plotting the solution using ParaView\n",
    "\n",
    "PyVista is useful for quick visualizations, but for\n",
    "more advanced visualizations an external tool must be used. In this\n",
    "section we demonstrate how to visualize solutions in ParaView.\n",
    "ParaView is a powerful\n",
    "tool for visualizing scalar and vector fields, including those\n",
    "computed by FEniCSx.\n",
    "\n",
    "The first step is to export the solution in VTX format:\n",
    "\n",
    "```python\n",
    "with io.VTXWriter(msh.comm, \"results/poisson.bp\", [uh]) as vtx:\n",
    "    vtx.write(0.0)\n",
    "```\n",
    "\n",
    "The following steps demonstrate how to create a plot of the solution\n",
    "of our Poisson problem in ParaView.\n",
    "\n",
    "1. Start the ParaView application.\n",
    "1. Click _File--Open..._ in the top menu and navigate to the directory containing the exported solution. This should be inside a subdirectory named `results` below the directory where the FEniCSx Python program was started. Select the file named `poisson.bp` and then click _OK_.\n",
    "1. Click _Apply_ in the Properties pane on the left. This will bring up a plot of the solution.\n",
    "1. To make a 3D plot of the solution, we will make use of one of ParaView's many *filters*. Click _Filters--Alphabetical--Warp By Scalar_ in the top menu and then _Apply_ in the Properties pane on the left. This create an elevated surface with the height determined by the solution value.\n",
    "1. To show the original plot below the elevated surface, click the little eye icon to the left of `poisson.bp` in the Pipeline Browser pane on the left. Also click the little 2D button at the top of the plot window to change the visualization to 3D. This lets you interact with the plot by rotating (left mouse button) and zooming (Ctrl + left mouse button).\n",
    "1. To show the finite element mesh, click on `poisson.bp` in the Pipeline Browser, navigate to _Representation_ in the Properties pane, and select _Surface With Edges_. This should make the finite element mesh visible.\n",
    "1. To change the aspect ratio of the plot, click on _WarpByScalar1_ in the Pipeline Browser and navigate to _Scale Factor_ in the Properties pane. Change the value to 0.2 and click _Apply_. This will change the scale of the warped plot. We also unclick _Orientation Axis Visibility_ at the bottom of the Properties pane to remove the little 3D axes in the lower left corner of the plot window.\n",
    "1. Finally, to export the visualization to a file, click _File--Save Screenshot..._ and select a suitable file name such as `poisson.png`."
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "fenicsx-env",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
